site_name: Hongnan G. PeekingDuck Projects
site_url: "https://reighns92.github.io/PeekingDuck-projects/"
nav:
  - Home: index.md
  - PeekingDuck:
    - Workflows: workflows.md
    - PeekingDuck Source Code Brief Tracing: pkd.md
    - Exercise Counter: exercise_counter.md
    - Melanoma Prediction with Grad-CAM: melanoma_gradcam.md
  - API Documentation: 
    - Exercise Counter: api/exercise_counter_api.md
theme:
  name: material
  features:
    - content.code.annotate
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - css/extra.css
plugins:
  - search
  - mkdocstrings