# Black formatting
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | _build
    | buck-out
    | build
    | dist
    | venv_pkd_exercise_counter
  )/
'''


# iSort
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
skip_gitignore = true
virtual_env = "venv_pkd_exercise_counter"
skip = "venv_pkd_exercise_counter"


# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"